version: '3.6'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: